[project]
name = "openss2"
version = "0.1.0"
readme = "README.md"
requires-python = "==3.10.*"

dependencies = [
    "torch==2.6.0",
    "torchvision==0.21.0",
    "torchaudio==2.6.0",
    "tyro==0.8.10",
    "numpy==1.26.4",
    "jaxtyping==0.3.1",
    "beartype==0.20.2",
    "lerobot",
    "transformers",
    "openpi-client",
]


[tool.ruff]
line-length = 88
indent-width = 4

target-version = "py310"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
ignore = ["F722"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"


[tool.uv.sources]
torch = { index = "pytorch" }
torchvision = { index = "pytorch" }
torchaudio = { index = "pytorch" }
lerobot = { git = "https://github.com/huggingface/lerobot", rev = "768e36660d1408c71118a2760f831c037fbfa17d" }
transformers = { git = "https://github.com/huggingface/transformers", rev = "6daa3eeba582facb57cd71db8efb66998b12942f"}
openpi-client = { path = "../openpi/packages/openpi-client" }


[[tool.uv.index]]
name = "mirror"
url = "https://pkg.pjlab.org.cn/repository/pypi-proxy/simple/"

[[tool.uv.index]]
name = "official"
url = "https://pypi.org/simple"

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu118"

[tool.uv]
allow-insecure-host = ["pkg.pjlab.org.cn"]